version: "3"

services:
  db:
    image: postgres
    volumes:
      - "./db/postgres_data:/var/lib/postgres/data"
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'

  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ".:/Rails_tutorial"
    tty: true
    stdin_open: true
    environment:
      - "DATABASE_PASSWORD=postgres"
    depends_on: 
      - db
